services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    environment:
      MONGO_URI: ${MONGO_URI}

  #backend:
  #  build:
  #    context: ./backend
  #    dockerfile: Dockerfile
  #  environment:
  #    MONGO_URI: ${MONGO_URI}



  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_LAWDB}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
  
volumes:
  mongo-data:
  mongo-config:
